services:

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1028
      - PGID=100
      - TZ=America/New_York
    ports:
      - 6767:6767
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/media/bazarr/data:/config
      - /volume1/data/media:/data/media
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=*****
      
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
      - PUID=1028
      - PGID=100
    ports:
      - 5055:5055
    volumes:
      - /volume1/docker/media/jellyseerr/data:/app/config
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=*****

  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PUID=1028
      - PGID=100
      - TZ=America/New_York
    ports:
      - 6789:6789
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/media/nzbget/data:/config:rw
      - /volume1/data/usenet:/data/usenet:rw
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=*****

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1028
      - PGID=100
      - TZ=America/New_York
    ports:
      - 9696:9696
    volumes:
      - /volume1/docker/media/prowlarr/data:/config
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=*****

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1028
      - PGID=100
      - TZ=America/New_York
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/media/radarr/data:/config
      - /volume1/data:/data
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=*****

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    init: true
    user: 1028:100
    volumes:
      - /volume1/docker/media/recyclarr/data:/config
    environment:
      - TZ=America/New_York

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1028
      - PGID=100
      - TZ=America/New_York
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/media/sonarr/data:/config
      - /volume1/data:/data
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=*****
