services:

  shreddit:
    container_name: shreddit
    image: mitchtalmadge/shreddit-dockerized:latest
    restart: unless-stopped
    volumes:
      - /volume1/docker/shreddit/data:/app/config
    environment:
      UID: 1026
      GID: 100
      CRON: "0 0 * * *"
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=*****
