services:

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=*****
